# Targeted sequencing type 
# 6 or 7 for Panel v6 and v7;
# SS5 or SS6 for SureSelect v5 and SureSelect v6
# TE for Twist_ComprehensiveExome
target: 6

# Reference genome version
# Either GRCh37 or GRCh38. Case insensitive
ref_gen: GRCh38

# Path to the Sarek's recalibrated.tsv output
#/nemo/project/proj-tracerX/working/SRM/RABIA/Preprocessing/TSV/recalibrated.tsv
recal: /nemo/project/proj-tracerX/working/SRM/RABIA/SAREK_1/Preprocessing/TSV/recalibrated.tsv

# VCF quality filter thresholds
ROQ: 20
AD: 4

## Rescue script path:
rescue: /nemo/project/proj-tracerX/working/PIPELINES/readOrientationBias_filtering_mutect2/v0.3/rescue_genotypes/annotate_allBams_info_indelsToo_forSarek_halfEmptyToo.py

