cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --partition=cpu
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name={rule}-{wildcards}
    --output={params.err}
    --error={params.err}
    --time={resources.time}
default-resources:
  - partition=cpu
  - mem_mb=1000
  - time="3-00:00:00"
restart-times: 3
local-cores: 1
latency-wait: 150
max-status-checks-per-second: 1
jobs: 500
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
